runtime: go123
instance_class: F1

handlers:
  - url: /.*
    script: auto

env_variables:
  GIN_MODE: "release"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5